backend:
  name: git-gateway
  #name: github
  #repo: daredoes/redirection
  branch: master

media_folder: static/assets
public_folder: assets

collections: # A list of collections the CMS should be able to edit
  - label: "Item"
    name: "item"
    folder: "bookmarks"
    create: true
    fields:
        - {label: "Name", name: "title", widget: "string"}
        - {label: "Description", name: "body", widget: "markdown", required: false}
        - {label: "Path", name: "path", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}
        - {label: "Public", name: "public", widget: "boolean", default: true}
        - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
        - label: "Tags"
          name: "tags"
          widget: "list"
          field: {label: "Tag", name:"tag", widget: "string"}
          default: []
          required: false
